### ISSUE TITLE
Registry dirty (low priority)

### ISSUE THREAD

**Issue by unkcpz** [sunoru/PkgMirrors.jl#14] opened 2019-11-05 12:55 UTC
```
(v1.2) pkg> up                                                                         
  Updating registry at `~/.julia/registries/General`
┌ Warning: Some registries failed to update:
│     — `~/.julia/registries/General` — registry dirty
└ @ Pkg.Types /build/julia/src/julia-1.2.0/usr/share/julia/stdlib/v1.2/Pkg/src/Types.jl:1171
  Updating git-repo `https://mirrors.zju.edu.cn/julia/PkgMirrors.jl.git`
```

According to https://discourse.julialang.org/t/registry-dirty/17989, the old `General` repository should be removed first.

Better to add this in the documentation.

**Comment by sunoru** [comment] 2020-03-10 18:22
Thanks for letting me know! This seemed to be caused by a bug in the package system that does not handle the same names with different casing correctly (QRUpdate and QRupdate in this case). And it should be fixed now :)

**Closed as completed by sunoru** 2020-03-10 18:22 UTC
